In [1]:
#Summing the Values in an Array¶

import numpy as np



In [5]:
L = np.random.random(100)
sum(L)

53.0200855287164

In [6]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

209 ms ± 32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.92 ms ± 80.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
#Minimum and Maximum

min(big_array), max(big_array)


(2.936912483209042e-07, 0.999998945641516)

In [8]:
np.min(big_array), np.max(big_array)


(2.936912483209042e-07, 0.999998945641516)

In [10]:
%timeit min(big_array)
%timeit np.min(big_array)

160 ms ± 56.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.51 ms ± 157 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
print(big_array.min(), big_array.max(), big_array.sum())


2.936912483209042e-07 0.999998945641516 499603.67008438666


In [12]:
#Multi dimensional aggregates

M = np.random.random((3, 4))
print(M)

[[0.13493277 0.45292692 0.75015697 0.21448211]
 [0.83732921 0.85401795 0.75327932 0.98405445]
 [0.43260114 0.99519083 0.51510354 0.85226699]]


In [13]:
M.sum()


7.776342200602032

In [14]:
M.min(axis=0)


array([0.13493277, 0.45292692, 0.51510354, 0.21448211])

In [15]:
M.max(axis=1)


array([0.75015697, 0.98405445, 0.99519083])

In [16]:

#Function Name	NaN-safe Version	Description
#np.sum	np.nansum	Compute sum of elements
#np.prod	np.nanprod	Compute product of elements
#np.mean	np.nanmean	Compute mean of elements
#np.std	np.nanstd	Compute standard deviation
#np.var	np.nanvar	Compute variance
#np.min	np.nanmin	Find minimum value
#np.max	np.nanmax	Find maximum value
#np.argmin	np.nanargmin	Find index of minimum value
#np.argmax	np.nanargmax	Find index of maximum value
#np.median	np.nanmedian	Compute median of elements
#np.percentile	np.nanpercentile	Compute rank-based statistics of elements
#np.any	N/A	Evaluate whether any elements are true
#np.all	N/A	Evaluate whether all elements are true
#We will see these aggregates often throughout the rest of the book.

In [ ]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)