In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)
compute_reciprocals(values)

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1, 100, size=100)
%timeit compute_reciprocals(big_array)

471 µs ± 86.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
big_array = np.random.randint(1, 100, size=1000)
%timeit compute_reciprocals(big_array)

5.43 ms ± 655 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
big_array = np.random.randint(1, 100, size=10000)
%timeit compute_reciprocals(big_array)

42.9 ms ± 5.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

4.55 s ± 1.01 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
#Introducing UFuncs
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [7]:
%timeit (1.0 / big_array)


10 ms ± 737 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [9]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [10]:
#Exploring NumPy's UFuncs
# Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary ufuncs, which operate on two inputs
# Array arithmetic
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [11]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [12]:
-(0.5*x + 1) ** 2


array([-1.  , -2.25, -4.  , -6.25])

In [13]:

#Operator	Equivalent ufunc	Description
#+	np.add	Addition (e.g., 1 + 1 = 2)
#-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
#-	np.negative	Unary negation (e.g., -2)
#*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
#/	np.divide	Division (e.g., 3 / 2 = 1.5)
#//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
#**	np.power	Exponentiation (e.g., 2 ** 3 = 8)
#%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

np.add(x, 2)

array([2, 3, 4, 5])

In [14]:
np.subtract(x, 2)

array([-2, -1,  0,  1])

In [15]:
np.multiply(x, 2)

array([0, 2, 4, 6])

In [16]:
#Absolute value
x = np.array([-2, -1, 0, 1, 2])
abs(x)


array([2, 1, 0, 1, 2])

In [17]:
np.absolute(x)


array([2, 1, 0, 1, 2])

In [18]:
np.abs(x)


array([2, 1, 0, 1, 2])

In [19]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])//????
np.abs(x)

SyntaxError: invalid syntax (<ipython-input-19-36b41bc11f73>, line 1)

In [ ]:
#Trigonometric functions
theta = np.linspace(0, np.pi, 3)


In [ ]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

In [ ]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

In [ ]:
#Exponents and logarithms

x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

In [ ]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

In [ ]:
#Specialized 
from scipy import special

# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

In [ ]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

In [ ]:
#Advanced Ufunc Features
#Specifying output

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

In [ ]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)


In [ ]:
#Aggregates
#calling reduce on the add ufunc returns the sum of all elements in the array:
x = np.arange(1, 6)
np.add.reduce(x)


In [ ]:
#calling reduce on the multiply ufunc results in the product of all array elements:
np.multiply.reduce(x)


In [ ]:
#store all the intermediate results of the computation, we can instead use accumulate
np.add.accumulate(x)



In [ ]:
np.multiply.accumulate(x)


In [ ]:
#Outer products¶

x = np.arange(1, 6)
np.multiply.outer(x, x)
