In [1]:
#Pandas
import pandas
pandas.__version__

'0.25.1'

In [2]:
import numpy as np
import pandas as pd

In [3]:
#The Pandas Series Object
#A Pandas Series is a one-dimensional array of indexed data
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values


array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[0]

0.25

In [7]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [8]:
#Series as generalized NumPy array
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
data['a']

0.25

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [11]:
data[5]

0.5

In [12]:
#Series as specialized dictionary
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [13]:
population['California']

38332521

In [14]:
#slicing
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [15]:
#Constructing Series objects
pd.Series([2, 4, 6])# integer sequence of index

0    2
1    4
2    6
dtype: int64

In [16]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [17]:
pd.Series({2:'a', 1:'b', 3:'c'})


2    a
1    b
3    c
dtype: object

In [18]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])


3    c
2    a
dtype: object

In [19]:
#DataFrame as a generalized NumPy array
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [20]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [21]:
states.index


Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [22]:
states.columns


Index(['population', 'area'], dtype='object')

In [23]:
states['area']


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [24]:
pd.DataFrame(population, columns=['population'])


population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [25]:
#From a list of dicts
#Any list of dictionaries can be made into a DataFrame
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [26]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])


a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [27]:
#From a dictionary of Series objects
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [28]:
#From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.020971  0.624012
b  0.515565  0.500502
c  0.445631  0.525385

In [29]:
#From a NumPy structured array
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A


array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [30]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [31]:
#The Pandas Index Object
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [32]:
#Index as immutable array
ind[1]


3

In [33]:
ind[::2]


Int64Index([2, 5, 11], dtype='int64')

In [34]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)


5 (5,) 1 int64


In [35]:
#Index as ordered set
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB  # intersection


Int64Index([3, 5, 7], dtype='int64')

In [36]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [37]:
indA ^ indB  # symmetric difference


Int64Index([1, 2, 9, 11], dtype='int64')

In [38]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [39]:
data['b']

0.5

In [40]:
'a' in data


True

In [41]:
data.keys()


Index(['a', 'b', 'c', 'd'], dtype='object')

In [42]:
data.keys()



Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
list(data.items())


[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [44]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [45]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [46]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [47]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [48]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [49]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [50]:
# explicit index when indexing
data[1]

'a'

In [51]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [52]:
data.loc[1]

'a'

In [53]:
data.loc[1:3]


1    a
3    b
dtype: object

In [54]:
data.iloc[1]


'b'

In [55]:
data.iloc[1:3]


3    b
5    c
dtype: object

In [56]:
#Data Selection in DataFrame
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [57]:
data['area']


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [58]:
data.area


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [59]:
data.area is data['area']
# attribute-style column access actually accesses the exact same object as the dictionary-style access:

True

In [60]:
data.pop is data['pop']


False

In [61]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [62]:
#DataFrame as two-dimensional array
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [63]:
data.T


California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [64]:
data.values[0]


array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [65]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [66]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [67]:
data.loc[:'Illinois', :'pop']


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [68]:
data.loc[data.density > 100, ['pop', 'density']]


pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [69]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [70]:
data['Florida':'Illinois']


area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [71]:
data[1:3]


area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [72]:
data[data.density > 100]


area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121