In [1]:
# NumPy Array Attributes

import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [3]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [4]:
print("dtype:", x1.dtype)
print("dtype:", x2.dtype)
print("dtype:", x3.dtype)


dtype: int32
dtype: int32
dtype: int32


In [5]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [8]:
# Array Indexing: Accessing Single Elements
x1


array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]


5

In [10]:
x1[4]

7

In [11]:
# To index from the end of the array, you can use negative indices:
x1[-1]

9

In [12]:
x1[-2]

7

In [13]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0,0]

3

In [16]:
x2[2,0]

1

In [17]:
x2[2]

array([1, 6, 7, 7])

In [18]:
x2[2,-1]

7

In [19]:
#Values can also be modified
x2[0,0] = 100

In [20]:
x2

array([[100,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [21]:
# NumPy Array has fixed type
x1[0] = 3.14159

In [22]:
# the value will be silently truncated
x1[0]

3

In [ ]:
# Array Slicing: Accessing Subarrays