In [1]:
import numpy
numpy.__version__

'1.16.5'

In [3]:
import numpy as np

In [6]:
# Help  !!!!
np?

In [7]:
# A Python List
#create a list of integers as follows:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(L[0])

int

In [9]:
 #a list of strings:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2[0])

str

In [11]:
# Because of Python's dynamic typing, we can even create heterogeneous lists:

L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

#But this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object

[bool, str, float, int]

In [12]:
# Fixed-Type Arrays in Python - uniform type!!!

import array
L = list(range(10))
# i implies array is of integers
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Creating Arrays from Python Lists -- same type
# integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [14]:
# if all dont belong to a type they upcast
# integer to floating point as we have one floating point i.e. 3.14
np.array([3.14, 4, 2, 3])


array([3.14, 4.  , 2.  , 3.  ])

In [15]:
# If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [16]:
# initializing a multidimensional array using a list of lists:
# note numpy array can be multidimensional unlike the python list
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [18]:
# Creating Arrays from Scratch
# Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. 

# Create a length-20 integer array filled with zeros
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Create a 3x5 array filled with 3.25
np.full((3, 5), 3.25)


array([[3.25, 3.25, 3.25, 3.25, 3.25],
       [3.25, 3.25, 3.25, 3.25, 3.25],
       [3.25, 3.25, 3.25, 3.25, 3.25]])

In [22]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.17246787, 0.37905226, 0.40704331],
       [0.58829359, 0.46345422, 0.37974113],
       [0.98587355, 0.80575457, 0.9881635 ]])

In [25]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.71156548, -0.88729032,  0.97710556],
       [ 0.73149349, -1.34462323,  0.9214113 ],
       [-1.7938865 ,  0.25487012, -1.56221054]])

In [26]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 7, 9],
       [6, 8, 3],
       [1, 4, 5]])

In [27]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
# explaination needed ??????????????????????????????????????????????????????????
np.empty(3)

array([1., 1., 1.])

In [29]:
np.zeros(10, dtype='int16')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [30]:
np.zeros(10, dtype=np.int16)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)